# Generated by Django 5.1.1 on 2024-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес объекта'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='completed_at',
            field=models.DateTimeField(null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='formed_at',
            field=models.DateTimeField(null=True, verbose_name='Дата формирования'),
        ),
    ]
