# Generated by Django 5.1.1 on 2024-09-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0002_alter_object_address_alter_voting_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votingobject',
            unique_together={('voting', 'object')},
        ),
    ]
