# Generated by Django 5.1.1 on 2024-09-23 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0003_alter_votingobject_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='votingobject',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.voting', verbose_name='Голосование'),
        ),
    ]
