# Generated by Django 5.1.1 on 2024-09-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0004_alter_votingobject_object_alter_votingobject_voting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='address',
        ),
    ]
