# Generated by Django 5.1.1 on 2024-10-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0005_remove_object_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Название голосования'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voting_date',
            field=models.DateTimeField(null=True, verbose_name='Дата голосования'),
        ),
    ]
