# Generated by Django 5.1.1 on 2024-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0006_alter_voting_title_alter_voting_voting_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votingobject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='votingobject',
            constraint=models.UniqueConstraint(fields=('voting', 'object'), name='unique_voting_object'),
        ),
    ]
