# Generated by Django 5.1.1 on 2024-10-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0007_alter_votingobject_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='formed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
    ]
