# Generated by Django 5.1.1 on 2024-10-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votings', '0009_voting_new_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='new_field',
            new_name='total_votes',
        ),
    ]
